/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export interface Address {
  /**
   * City name
   * @nullable
   */
  city?: string | null;
  /**
   * District name
   * @nullable
   */
  district?: string | null;
  /** Latitude of the address */
  lat: string;
  /** Longitude of the address */
  lng: string;
  /**
   * Metro station name
   * @nullable
   */
  metro?: string | null;
  /** Street name */
  street: string;
}
