/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export interface FilterByDto {
  /** The pharmacy name */
  apteka?: string;
  /** The district ID */
  district?: number;
  /** The metro ID */
  metro?: number;
  /** The region ID */
  region?: number;
}
