/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

/**
 * Sort by criteria
 */
export type ListPositionsBodyDtoSortBy =
  (typeof ListPositionsBodyDtoSortBy)[keyof typeof ListPositionsBodyDtoSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListPositionsBodyDtoSortBy = {
  default: "default",
  price: "price",
} as const;
