/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { FilterByDto } from "./filterByDto";
import type { ListPositionsBodyDtoSortBy } from "./listPositionsBodyDtoSortBy";
import type { ProductDto } from "./productDto";

export interface ListPositionsBodyDto {
  /** Filter criteria */
  filterBy?: FilterByDto;
  /** Page number */
  page?: number;
  /** The product details */
  product: ProductDto;
  /** Flag to search by all trade names */
  searchByAllTradeNames: boolean;
  /** Sort by criteria */
  sortBy?: ListPositionsBodyDtoSortBy;
}
