/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export interface PaginationDto {
  /** End index of the pagination */
  end: number;
  /** Start index of the pagination */
  start: number;
}
