/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { Address } from "./address";

export interface Pharmacy {
  /** Address of the pharmacy */
  address: Address;
  /** Flag indicating if the pharmacy works 24/7 */
  allhours: boolean;
  /** Unique identifier of the pharmacy */
  id: string;
  /** Name of the pharmacy */
  name: string;
  /** Phone number of the pharmacy */
  phone: string;
  /**
   * Last update time
   * @nullable
   */
  updateTime?: string | null;
  /**
   * Work time
   * @nullable
   */
  workTime?: string | null;
}
