/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

/**
 * Sort by criteria
 */
export type PositionsListBodyDtoSortBy =
  (typeof PositionsListBodyDtoSortBy)[keyof typeof PositionsListBodyDtoSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PositionsListBodyDtoSortBy = {
  default: "default",
  price: "price",
} as const;
