/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { PaginationDto } from "./paginationDto";
import type { Position } from "./position";

export interface PositionsListResponseDto {
  /** Total count of positions */
  count: number;
  /** Pagination details */
  pagination: PaginationDto;
  /** List of positions */
  positions: Position[];
}
