/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { FilterByDto } from "./filterByDto";
import type { PositionsListBodyDtoSortBy } from "./positionsListBodyDtoSortBy";
import type { ProductDto } from "./productDto";

export interface PositionsListBodyDto {
  /** Filter criteria */
  filterBy?: FilterByDto;
  /** Page number */
  page?: number;
  /** The product details */
  product: ProductDto;
  /** Sort by criteria */
  sortBy?: PositionsListBodyDtoSortBy;
}
