/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

/**
 * Pharmacological group of the product
 * @nullable
 */
export type ProductPharmacologicalGroup = { [key: string]: unknown } | null;
