/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export interface Product {
  /**
   * Active substance of the product
   * @nullable
   */
  activeSubstance?: string | null;
  /**
   * Dosage of the product
   * @nullable
   */
  dosage?: string | null;
  /** Unique identifier of the product */
  id: string;
  /** Название продукта для отображения в ui */
  label: string;
  /** Сырое (оригинальное) название из данных */
  name: string;
  /**
   * Origin country of the product
   * @nullable
   */
  originCountry?: string | null;
  /**
   * Pharmacological group of the product
   * @nullable
   */
  pharmacologicalGroup?: string | null;
}
