/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { Product } from "./product";

export interface ProductsListDto {
  /** Active product */
  active?: Product;
  /** List of products */
  products: Product[];
}
