/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export interface Tip {
  /** Unique identifier of the tip */
  id: string;
  /** Name of the tip */
  name: string;
}
