/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export type TipFindAllParams = {
  /**
   * Name of the product to search tips for
   */
  q: string;
  limit?: number;
};
